service: serverless-github-check-js 

custom:
  environment: ${file(.env.yml):default}

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    GITHUB_TOKEN: ${self:custom.environment.GITHUB_TOKEN}

functions:
  checker:
    handler: handler.checker
    events:
      - http:
          method: post
          path: /

